
import {createContext, React } from "react";
const countriescontext = createContext();

const Countries = (props) => {

    const countryCodes = [
        { value: '+1', label: '+1 (USA)' },
        { value: '+44', label: '+44 (UK)' },
        { value: '+61', label: '+61 (Australia)' },
        { value: '+33', label: '+33 (France)' },
        { value: '+81', label: '+81 (Japan)' },
        { value: '+86', label: '+86 (China)' },
      { value: '+49', label: '+49 (Germany)' },
      { value: '+39', label: '+39 (Italy)' },
      { value: '+52', label: '+52 (Mexico)' },
      { value: '+31', label: '+31 (Netherlands)' },
      { value: '+7', label: '+7 (Russia)' },
      { value: '+65', label: '+65 (Singapore)' },
      { value: '+27', label: '+27 (South Africa)' },
      { value: '+34', label: '+34 (Spain)' },
      { value: '+46', label: '+46 (Sweden)' },
      { value: '+41', label: '+41 (Switzerland)' },
      { value: '+90', label: '+90 (Turkey)' },
      { value: '+971', label: '+971 (United Arab Emirates)' },
      { value: '+598', label: '+598 (Uruguay)' },
      { value: '+58', label: '+58 (Venezuela)' },
      { value: '+84', label: '+84 (Vietnam)' },
      { value: '+967', label: '+967 (Yemen)' },
      { value: '+260', label: '+260 (Zambia)' },
      { value: '+263', label: '+263 (Zimbabwe)' },
      { value: '+92', label: '+92 (Pakistan)' },
      { value: '+971', label: '+971 (UAE)' },
      { value: '+44', label: '+44 (England)' },
      { value: '+91', label: '+91 (India)' },
      { value: '+880', label: '+880 (Bangladesh)' },
      { value: '+94', label: '+94 (Sri Lanka)' },
        // Add more country codes as needed
      ];
    
    const countries = [
        { label: "Andorra" },
        { label: "United Arab Emirates" },
        { label: "Afghanistan" },
        { label: "Antigua and Barbuda" },
        { label: "Anguilla" },
        { label: "Albania" },
        { label: "Armenia" },
        { label: "Angola" },
        { label: "Antarctica" },
        { label: "Argentina" },
        { label: "American Samoa" },
        { label: "Austria" },
        { label: "Australia", suggested: true },
        { label: "Aruba" },
        { label: "Alland Islands" },
        { label: "Azerbaijan" },
        { label: "Bosnia and Herzegovina" },
        { label: "Barbados" },
        { label: "Bangladesh" },
        { label: "Belgium" },
        { label: "Burkina Faso" },
        { label: "Bulgaria" },
        { label: "Bahrain" },
        { label: "Burundi" },
        { label: "Benin" },
        { label: "Saint Barthelemy" },
        { label: "Bermuda" },
        { label: "Brunei Darussalam" },
        { label: "Bolivia" },
        { label: "Brazil" },
        { label: "Bahamas" },
        { label: "Bhutan" },
        { label: "Bouvet Island" },
        { label: "Botswana" },
        { label: "Belarus" },
        { label: "Belize" },
        { label: "Canada", suggested: true },
        { label: "Cocos (Keeling) Islands" },
        { label: "Congo, Democratic Republic of the" },
        { label: "Central African Republic" },
        { label: "Congo, Republic of the" },
        { label: "Switzerland" },
        { label: "Cote d'Ivoire" },
        { label: "Cook Islands" },
        { label: "Chile" },
        { label: "Cameroon" },
        { label: "China" },
        { label: "Colombia" },
        { label: "Costa Rica" },
        { label: "Cuba" },
        { label: "Cape Verde" },
        { label: "Curacao" },
        { label: "Christmas Island" },
        { label: "Cyprus" },
        { label: "Czech Republic" },
        { label: "Germany", suggested: true },
        { label: "Djibouti" },
        { label: "Denmark" },
        { label: "Dominica" },
        { label: "Dominican Republic" },
        { label: "Algeria" },
        { label: "Ecuador" },
        { label: "Estonia" },
        { label: "Egypt" },
        { label: "Western Sahara" },
        { label: "Eritrea" },
        { label: "Spain" },
        { label: "Ethiopia" },
        { label: "Finland" },
        { label: "Fiji" },
        { label: "Falkland Islands (Malvinas)" },
        { label: "Micronesia, Federated States of" },
        { label: "Faroe Islands" },
        { label: "France" },
        { label: "Gabon" },
        { label: "United Kingdom" },
        { label: "Grenada" },
        { label: "Georgia" },
        { label: "French Guiana" },
        { label: "Guernsey" },
        { label: "Ghana" },
        { label: "Gibraltar" },
        { label: "Greenland" },
        { label: "Gambia" },
        { label: "Guinea" },
        { label: "Guadeloupe" },
        { label: "Equatorial Guinea" },
        { label: "Greece" },
        { label: "South Georgia and the South Sandwich Islands" },
        { label: "Guatemala" },
        { label: "Guam" },
        { label: "Guinea-Bissau" },
        { label: "Guyana" },
        { label: "Hong Kong" },
        { label: "Heard Island and McDonald Islands" },
        { label: "Honduras" },
        { label: "Croatia" },
        { label: "Haiti" },
        { label: "Hungary" },
        { label: "Indonesia" },
        { label: "Ireland" },
        { label: "Israel" },
        { label: "Isle of Man" },
        { label: "India" },
        { label: "British Indian Ocean Territory" },
        { label: "Iraq" },
        { label: "Iran, Islamic Republic of" },
        { label: "Iceland" },
        { label: "Italy" },
        { label: "Jersey" },
        { label: "Jamaica" },
        { label: "Jordan" },
        { label: "Japan", suggested: true },
        { label: "Kenya" },
        { label: "Kyrgyzstan" },
        { label: "Cambodia" },
        { label: "Kiribati" },
        { label: "Comoros" },
        { label: "Saint Kitts and Nevis" },
        { label: "Korea, Democratic People's Republic of" },
        { label: "Korea, Republic of" },
        { label: "Kuwait" },
        { label: "Cayman Islands" },
        { label: "Kazakhstan" },
        { label: "Lao People's Democratic Republic" },
        { label: "Lebanon" },
        { label: "Saint Lucia" },
        { label: "Liechtenstein" },
        { label: "Sri Lanka" },
        { label: "Liberia" },
        { label: "Lesotho" },
        { label: "Lithuania" },
        { label: "Luxembourg" },
        { label: "Latvia" },
        { label: "Libya" },
        { label: "Morocco" },
        { label: "Monaco" },
        { label: "Moldova, Republic of" },
        { label: "Montenegro" },
        { label: "Saint Martin (French part)" },
        { label: "Madagascar" },
        { label: "Marshall Islands" },
        { label: "Macedonia, the Former Yugoslav Republic of" },
        { label: "Mali" },
        { label: "Myanmar" },
        { label: "Mongolia" },
        { label: "Macao" },
        { label: "Northern Mariana Islands" },
        { label: "Martinique" },
        { label: "Mauritania" },
        { label: "Montserrat" },
        { label: "Malta" },
        { label: "Mauritius" },
        { label: "Maldives" },
        { label: "Malawi" },
        { label: "Mexico" },
        { label: "Malaysia" },
        { label: "Mozambique" },
        { label: "Namibia" },
        { label: "New Caledonia" },
        { label: "Niger" },
        { label: "Norfolk Island" },
        { label: "Nigeria" },
        { label: "Nicaragua" },
        { label: "Netherlands" },
        { label: "Norway" },
        { label: "Nepal" },
        { label: "Nauru" },
        { label: "Niue" },
        { label: "New Zealand" },
        { label: "Oman" },
        { label: "Panama" },
        { label: "Peru" },
        { label: "French Polynesia" },
        { label: "Papua New Guinea" },
        { label: "Philippines" },
        { label: "Pakistan" },
        { label: "Poland" },
        { label: "Saint Pierre and Miquelon" },
        { label: "Pitcairn" },
        { label: "Puerto Rico" },
        { label: "Palestine, State of" },
        { label: "Portugal" },
        { label: "Palau" },
        { label: "Paraguay" },
        { label: "Qatar" },
        { label: "Reunion" },
        { label: "Romanian" },
        { label: "Serbia" },
        { label: "Russian Federation" },
        { label: "Rwanda" },
        { label: "Saudi Arabia" },
        { label: "Solomon Islands" },
        { label: "Seychelles" },
        { label: "Sudan" },
        { label: "Sweden" },
        { label: "Singapore" },
        { label: "Saint Helena" },
        { label: "Slovenia" },
        { label: "Svalbard and Jan Mayen" },
        { label: "Slovakia" },
        { label: "Sierra Leone" },
        { label: "San Marino" },
        { label: "Senegal" },
        { label: "Somalia" },
        { label: "Suriname" },
        { label: "South Sudan" },
        { label: "Sao Tome and Principe" },
        { label: "El Salvador" },
        { label: "Sint Maarten (Dutch part)" },
        { label: "Syrian Arab Republic" },
        { label: "Swaziland" },
        { label: "Turks and Caicos Islands" },
        { label: "Chad" },
        { label: "French Southern Territories" },
        { label: "Togo" },
        { label: "Thailand", phone: "66" },
        { label: "Tajikistan", phone: "992" },
        { label: "Tokelau", phone: "690" },
        { label: "Timor-Leste", phone: "670" },
        { label: "Turkmenistan", phone: "993" },
        { label: "Tunisia", phone: "216" },
        { label: "Tonga", phone: "676" },
        { label: "Turkey", phone: "90" },
        { label: "Trinidad and Tobago" },
        { label: "Tuvalu" },
        { label: "Taiwan, Republic of China" },
        { label: "United Republic of Tanzania" },
        { label: "Ukraine" },
        { label: "Uganda" },
        { label: "United States" },
        { label: "Uruguay" },
        { label: "Uzbekistan" },
        { label: "Holy See (Vatican City State)" },
        { label: "Saint Vincent and the Grenadines" },
        { label: "Venezuela" },
        { label: "British Virgin Islands" },
        { label: "US Virgin Islands" },
        { label: "Vietnam" },
        { label: "Vanuat" },
        { label: "Wallis and Futuna" },
        { label: "Samoa" },
        { label: "Kosovo" },
        { label: "Yemen" },
        { label: "Mayotte" },
        { label: "South Afric" },
        { label: "Zambia" },
        { label: "Zimbabwe" },
      ];

      

  return (
    <countriescontext.Provider value={{countries,countryCodes}}>
        {props.children}
    </countriescontext.Provider>
  )
}

export default Countries
export {countriescontext};
